In [2]:
import pandas as pd

df = pd.read_csv("../datasets/raw/ufc-master.csv")

In [3]:
df.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
0,Israel Adesanya,Joe Pyfer,-130.0,102.0,76.9231,102.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,Punches,2.0,4:18,558.0,163.0,900.0,2500.0,400.0,300.0,250.0
1,Alexa Grasso,Maycee Barber,124.0,-158.0,124.0000,63.2911,2026-03-28,"Seattle, Washington, USA",USA,Red,...,Punch,1.0,2:42,162.0,175.0,105.0,1400.0,800.0,2500.0,500.0
2,Michael Chiesa,Niko Price,-901.0,550.0,11.0988,550.0000,2026-03-28,"Seattle, Washington, USA",USA,Red,...,Rear Naked Choke,1.0,1:03,63.0,225.0,900.0,-150.0,1600.0,600.0,1000.0
3,Julian Erosa,Lerryan Douglas,235.0,-320.0,235.0000,31.2500,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,Punches,1.0,3:33,213.0,600.0,500.0,600.0,2000.0,700.0,-150.0
4,Mansur Abdul-Malik,Yousri Belgaroui,-158.0,124.0,63.2911,124.0000,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,Knee,3.0,3:39,819.0,350.0,240.0,800.0,1800.0,240.0,250.0

In [5]:
df.shape

(7177, 118)

In [6]:
df.columns

Index(['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date',
       'location', 'country', 'Winner',
       ...
       'finish_details', 'finish_round', 'finish_round_time',
       'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds',
       'b_sub_odds', 'r_ko_odds', 'b_ko_odds'],
      dtype='str', length=118)

In [8]:
df.columns.to_list()

['R_fighter',
 'B_fighter',
 'R_odds',
 'B_odds',
 'R_ev',
 'B_ev',
 'date',
 'location',
 'country',
 'Winner',
 'title_bout',
 'weight_class',
 'gender',
 'no_of_rounds',
 'B_current_lose_streak',
 'B_current_win_streak',
 'B_draw',
 'B_avg_SIG_STR_landed',
 'B_avg_SIG_STR_pct',
 'B_avg_SUB_ATT',
 'B_avg_TD_landed',
 'B_avg_TD_pct',
 'B_longest_win_streak',
 'B_losses',
 'B_total_rounds_fought',
 'B_total_title_bouts',
 'B_win_by_Decision_Majority',
 'B_win_by_Decision_Split',
 'B_win_by_Decision_Unanimous',
 'B_win_by_KO/TKO',
 'B_win_by_Submission',
 'B_win_by_TKO_Doctor_Stoppage',
 'B_wins',
 'B_Stance',
 'B_Height_cms',
 'B_Reach_cms',
 'B_Weight_lbs',
 'R_current_lose_streak',
 'R_current_win_streak',
 'R_draw',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct',
 'R_avg_SUB_ATT',
 'R_avg_TD_landed',
 'R_avg_TD_pct',
 'R_longest_win_streak',
 'R_losses',
 'R_total_rounds_fought',
 'R_total_title_bouts',
 'R_win_by_Decision_Majority',
 'R_win_by_Decision_Split',
 'R_win_by_Decision_Unanimous',
 'R_win_by_KO/TKO',
 'R_win_by_Submission',
 'R_win_by_TKO_Doctor_Stoppage',
 'R_wins',
 'R_Stance',
 'R_Height_cms',
 'R_Reach_cms',
 'R_Weight_lbs',
 'R_age',
 'B_age',
 'lose_streak_dif',
 'win_streak_dif',
 'longest_win_streak_dif',
 'win_dif',
 'loss_dif',
 'total_round_dif',
 'total_title_bout_dif',
 'ko_dif',
 'sub_dif',
 'height_dif',
 'reach_dif',
 'age_dif',
 'sig_str_dif',
 'avg_sub_att_dif',
 'avg_td_dif',
 'empty_arena',
 'B_match_weightclass_rank',
 'R_match_weightclass_rank',
 "R_Women's Flyweight_rank",
 "R_Women's Featherweight_rank",
 "R_Women's Strawweight_rank",
 "R_Women's Bantamweight_rank",
 'R_Heavyweight_rank',
 'R_Light Heavyweight_rank',
 'R_Middleweight_rank',
 'R_Welterweight_rank',
 'R_Lightweight_rank',
 'R_Featherweight_rank',
 'R_Bantamweight_rank',
 'R_Flyweight_rank',
 'R_Pound-for-Pound_rank',
 "B_Women's Flyweight_rank",
 "B_Women's Featherweight_rank",
 "B_Women's Strawweight_rank",
 "B_Women's Bantamweight_rank",
 'B_Heavyweight_rank',
 'B_Light Heavyweight_rank',
 'B_Middleweight_rank',
 'B_Welterweight_rank',
 'B_Lightweight_rank',
 'B_Featherweight_rank',
 'B_Bantamweight_rank',
 'B_Flyweight_rank',
 'B_Pound-for-Pound_rank',
 'better_rank',
 'finish',
 'finish_details',
 'finish_round',
 'finish_round_time',
 'total_fight_time_secs',
 'r_dec_odds',
 'b_dec_odds',
 'r_sub_odds',
 'b_sub_odds',
 'r_ko_odds',
 'b_ko_odds']

In [9]:
len([c for c in df.columns if c.startswith("R_")])

41

In [10]:
len([c for c in df.columns if c.startswith("B_")])

41

In [11]:
[c for c in df.columns if "SIG" in c]

['B_avg_SIG_STR_landed',
 'B_avg_SIG_STR_pct',
 'R_avg_SIG_STR_landed',
 'R_avg_SIG_STR_pct']

In [12]:
[c for c in df.columns if "TD" in c]

['B_avg_TD_landed', 'B_avg_TD_pct', 'R_avg_TD_landed', 'R_avg_TD_pct']

In [13]:
[c for c in df.columns if "height" in c.lower() or "reach" in c.lower()]

['B_Height_cms',
 'B_Reach_cms',
 'R_Height_cms',
 'R_Reach_cms',
 'height_dif',
 'reach_dif']

In [14]:
fighter = "Israel Adesanya"

red = df[df["R_fighter"] == fighter]
blue = df[df["B_fighter"] == fighter]

print("Red corner fights:", len(red))
print("Blue corner fights:", len(blue))

Red corner fights: 11
Blue corner fights: 8

In [15]:
red.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
0,Israel Adesanya,Joe Pyfer,-130.0,102.0,76.9231,102.0,2026-03-28,"Seattle, Washington, USA",USA,Blue,...,Punches,2.0,4:18,558.0,163.0,900.0,2500.0,400.0,300.0,250.0
598,Israel Adesanya,Nassourdine Imavov,-158.0,134.0,63.2911,134.0,2025-02-01,"Riyadh, Riyadh, Saudi Arabia",Saudi Arabia,Blue,...,Punch,2.0,0:30,330.0,140.0,310.0,2600.0,900.0,2200.0,2000.0
1269,Israel Adesanya,Sean Strickland,-550.0,410.0,18.1818,410.0,2023-09-09,"Sydney, New South Wales, Australia",Australia,Blue,...,NaN,5.0,5:00,1500.0,165.0,1400.0,1600.0,2000.0,-125.0,1000.0
1702,Israel Adesanya,Alex Pereira,-210.0,180.0,47.6190,180.0,2022-11-12,"New York City, New York, USA",USA,Blue,...,Punches,5.0,2:01,1321.0,120.0,850.0,1400.0,2800.0,275.0,275.0
1892,Israel Adesanya,Jared Cannonier,-540.0,420.0,18.5185,420.0,2022-07-02,"Las Vegas, Nevada, USA",USA,Red,...,NaN,5.0,5:00,1500.0,120.0,1100.0,1400.0,2500.0,130.0,650.0

In [16]:
blue.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
807,Dricus Du Plessis,Israel Adesanya,-120.0,100.0,83.3333,100.0000,2024-08-17,"Perth, Western Australia, Australia",Australia,Red,...,Rear Naked Choke,4.0,3:38,1118.0,400.0,250.0,600.0,2500.0,275.0,275.0
1521,Alex Pereira,Israel Adesanya,NaN,NaN,NaN,NaN,2023-04-08,"Miami, Florida, USA",USA,Blue,...,Punch,2.0,4:21,561.0,NaN,NaN,NaN,NaN,NaN,NaN
2566,Jan Blachowicz,Israel Adesanya,205.0,-245.0,205.0000,40.8163,2021-03-06,"Las Vegas, Nevada, USA",USA,Red,...,NaN,NaN,NaN,NaN,800.0,235.0,800.0,1600.0,325.0,135.0
3213,Robert Whittaker,Israel Adesanya,110.0,-130.0,110.0000,76.9231,2019-10-05,"Melbourne, Victoria, Australia",Australia,Blue,...,Punch,2.0,3:33,513.0,315.0,300.0,1400.0,1500.0,230.0,240.0
3475,Kelvin Gastelum,Israel Adesanya,150.0,-170.0,150.0000,58.8235,2019-04-13,"Atlanta, Georgia, USA",USA,Blue,...,NaN,5.0,5:00,1500.0,700.0,160.0,600.0,1400.0,325.0,250.0

In [21]:
def scout_card(name):
    red = df[df["R_fighter"] == name]
    blue = df[df["B_fighter"] == name]

    total_fights = len(red) + len(blue)


    

    print("=" * 40)
    print(name.upper())
    print("=" * 40)
    print(f"Total UFC Fights : {total_fights}")
    print(f"Red Corner       : {len(red)}")
    print(f"Blue Corner      : {len(blue)}")

    red_wins = len(red[red["Winner"] == "Red"])
    blue_wins = len(blue[blue["Winner"] == "Blue"])

    wins = red_wins + blue_wins
    losses = total_fights - wins

    print(f"Wins             : {wins}")
    print(f"Losses           : {losses}")

In [22]:
scout_card("Israel Adesanya")

========================================
ISRAEL ADESANYA
========================================
Total UFC Fights : 19
Red Corner       : 11
Blue Corner      : 8
Wins             : 13
Losses           : 6