### Phase 3: Exploratory Data Analysis (EDA)

In [12]:
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv("../datasets/raw/ufc-master.csv")

gladiator = pd.read_csv("../datasets/processed/gladiator_v1.csv")

In [13]:
gladiator.head()

,winner,fighter_red,fighter_blue,age_diff,height_diff,reach_diff,sig_strike_diff,sig_accuracy_diff,td_diff,td_accuracy_diff,submission_diff,wins_diff,losses_diff,win_streak_diff,lose_streak_diff,strike_defense_diff,td_defense_diff,title_fight,rounds
0,Blue,Israel Adesanya,Joe Pyfer,7,5.08,12.70,0.51,0.04,-1.40,-0.21,-0.8,6,3,-3,3,0.04,-0.21,False,5
1,Red,Alexa Grasso,Maycee Barber,5,0.00,2.54,-0.45,-0.12,-1.16,-0.10,0.6,-3,3,-7,2,-0.12,-0.10,False,3
2,Red,Michael Chiesa,Niko Price,2,2.54,-2.54,-3.09,-0.03,2.05,0.17,0.4,6,-3,3,-3,-0.03,0.17,False,3
3,Blue,Julian Erosa,Lerryan Douglas,6,10.16,5.08,-2.49,-0.16,1.73,0.43,0.7,9,8,-1,1,-0.16,0.43,False,3
4,Blue,Mansur Abdul-Malik,Yousri Belgaroui,-5,-10.16,2.54,-2.82,-0.20,1.36,-0.59,0.3,2,-1,2,0,-0.20,-0.59,False,3

In [14]:
gladiator.shape

(7177, 19)

In [15]:
gladiator.info()

<class 'pandas.DataFrame'>
RangeIndex: 7177 entries, 0 to 7176
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   winner               7177 non-null   str
 1   fighter_red          7177 non-null   str
 2   fighter_blue         7177 non-null   str
 3   age_diff             7177 non-null   int64
 4   height_diff          7177 non-null   float64
 5   reach_diff           7177 non-null   float64
 6   sig_strike_diff      6136 non-null   float64
 7   sig_accuracy_diff    6290 non-null   float64
 8   td_diff              6233 non-null   float64
 9   td_accuracy_diff     6224 non-null   float64
 10  submission_diff      6234 non-null   float64
 11  wins_diff            7177 non-null   int64
 12  losses_diff          7177 non-null   int64
 13  win_streak_diff      7177 non-null   int64
 14  lose_streak_diff     7177 non-null   int64
 15  strike_defense_diff  6290 non-null   float64
 16  td_defense_diff      6224 non-null   float64
 17  title_fight          7177 non-null   bool
 18  rounds               7177 non-null   int64
dtypes: bool(1), float64(9), int64(6), str(3)
memory usage: 1016.4 KB

In [16]:
gladiator.isnull().sum()

winner                    0
fighter_red               0
fighter_blue              0
age_diff                  0
height_diff               0
reach_diff                0
sig_strike_diff        1041
sig_accuracy_diff       887
td_diff                 944
td_accuracy_diff        953
submission_diff         943
wins_diff                 0
losses_diff               0
win_streak_diff           0
lose_streak_diff          0
strike_defense_diff     887
td_defense_diff         953
title_fight               0
rounds                    0
dtype: int64

In [17]:
missing = gladiator.isnull().sum()

missing[missing > 0]

sig_strike_diff        1041
sig_accuracy_diff       887
td_diff                 944
td_accuracy_diff        953
submission_diff         943
strike_defense_diff     887
td_defense_diff         953
dtype: int64

In [18]:
gladiator.isnull().sum().sum()

np.int64(6608)

In [19]:
(gladiator.isnull().mean() * 100).round(2)

winner                  0.00
fighter_red             0.00
fighter_blue            0.00
age_diff                0.00
height_diff             0.00
reach_diff              0.00
sig_strike_diff        14.50
sig_accuracy_diff      12.36
td_diff                13.15
td_accuracy_diff       13.28
submission_diff        13.14
wins_diff               0.00
losses_diff             0.00
win_streak_diff         0.00
lose_streak_diff        0.00
strike_defense_diff    12.36
td_defense_diff        13.28
title_fight             0.00
rounds                  0.00
dtype: float64

In [20]:
df[df["R_avg_SIG_STR_landed"].isnull()][
    [
        "R_fighter",
        "B_fighter",
        "R_wins",
        "B_wins",
        "R_losses",
        "B_losses",
        "date"
    ]
].head(20)

,R_fighter,B_fighter,R_wins,B_wins,R_losses,B_losses,date
3081,Curtis Blaydes,Junior Dos Santos,7,15,2,5,2020-01-25
3082,Rafael Dos Anjos,Michael Chiesa,18,9,10,4,2020-01-25
3083,Jordan Espinosa,Alex Perez,1,4,1,1,2020-01-25
3084,Hannah Cifers,Angela Hill,2,5,1,7,2020-01-25
3085,Jamahal Hill,Darko Stosic,0,1,0,2,2020-01-25
3086,Bevon Lewis,Dequan Townsend,0,0,2,1,2020-01-25
3087,Arnold Allen,Nik Lentz,6,14,0,7,2020-01-25
3088,Justine Kish,Luci Pudilova,2,2,2,4,2020-01-25
3089,Montel Jackson,Felipe Colares,2,1,1,1,2020-01-25
3090,Sara McMann,Lina Lansberg,9,4,5,3,2020-01-25
3091,Brett Johns,Tony Gravely,3,0,2,0,2020-01-25
3092,Herbert Burns,Nate Landwehr,0,0,0,0,2020-01-25
3093,Conor McGregor,Donald Cerrone,9,23,2,10,2020-01-18
3094,Holly Holm,Raquel Pennington,5,7,5,4,2020-01-18
3095,Aleksei Oleinik,Maurice Greene,6,3,4,1,2020-01-18
3096,Anthony Pettis,Diego Ferreira,9,7,8,2,2020-01-18
3097,Roxanne Modafferi,Maycee Barber,2,3,4,0,2020-01-18
3098,Andre Fili,Sodiq Yusuff,8,3,5,0,2020-01-18
3099,Drew Dober,Nasrat Haqparast,8,3,5,1,2020-01-18
3100,Aleksa Camur,Justin Ledet,0,3,0,2,2020-01-18

In [21]:
df[df["R_fighter"] == "Curtis Blaydes"].T

,385,1057,1855,2037,2295,2589,2932,3081,3261,3501,3673
R_fighter,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes,Curtis Blaydes
B_fighter,Rizvan Kuniev,Jailton Almeida,Tom Aspinall,Chris Daukaus,Jairzinho Rozenstruik,Derrick Lewis,Alexander Volkov,Junior Dos Santos,Shamil Abdurakhimov,Justin Willis,Francis Ngannou
R_odds,-240.0,114.0,135.0,-600.0,-380.0,-400.0,-400.0,-280.0,-550.0,-275.0,-240.0
B_odds,198.0,-135.0,-155.0,435.0,290.0,300.0,325.0,240.0,425.0,235.0,200.0
R_ev,41.6667,114.0,135.0,16.6667,26.3158,25.0,25.0,35.7143,18.1818,36.3636,41.6667
...,...,...,...,...,...,...,...,...,...,...,...
b_dec_odds,500.0,450.0,650.0,1600.0,1000.0,1200.0,800.0,1200.0,1000.0,600.0,1600.0
r_sub_odds,1900.0,2000.0,1400.0,800.0,1000.0,550.0,1150.0,1000.0,1200.0,900.0,1000.0
b_sub_odds,1300.0,275.0,550.0,1600.0,3500.0,2500.0,2000.0,1400.0,1400.0,1800.0,1600.0
r_ko_odds,140.0,225.0,240.0,-120.0,125.0,-175.0,-230.0,-110.0,100.0,150.0,-110.0
b_ko_odds,550.0,400.0,140.0,500.0,380.0,400.0,483.0,325.0,700.0,400.0,210.0

In [22]:
df.loc[
    df["R_fighter"] == "Curtis Blaydes",
    [
        "date",
        "R_avg_SIG_STR_landed",
        "R_avg_SIG_STR_pct",
        "R_avg_TD_landed",
        "R_avg_TD_pct",
        "R_avg_SUB_ATT"
    ]
]

,date,R_avg_SIG_STR_landed,R_avg_SIG_STR_pct,R_avg_TD_landed,R_avg_TD_pct,R_avg_SUB_ATT
385,2025-06-21,3.5600,0.500,5.3800,0.480,0.0
1057,2024-03-09,3.5400,0.500,5.6900,0.530,0.0
1855,2022-07-23,3.5400,0.500,5.6900,0.530,0.0
2037,2022-03-26,3.5400,0.500,5.6900,0.530,0.0
2295,2021-09-25,3.4400,0.510,6.2700,0.530,0.0
2589,2021-02-20,3.5900,0.530,6.6400,0.540,0.0
2932,2020-06-20,3.7400,0.510,6.6300,0.550,0.0
3081,2020-01-25,NaN,0.510,7.0500,0.600,0.0
3261,2019-09-07,3.7400,0.510,6.6300,0.550,0.0
3501,2019-03-23,38.2500,0.493,4.1250,0.584,0.0
3673,2018-11-24,43.5714,0.546,4.7143,0.667,0.0

In [23]:
df["R_avg_SIG_STR_landed"].describe()

count    6722.000000
mean       19.529597
std        19.547405
min         0.000000
25%         3.990000
50%         8.170000
75%        32.000000
max       141.000000
Name: R_avg_SIG_STR_landed, dtype: float64

In [24]:
df["R_avg_SIG_STR_landed"].sort_values(ascending=False).head(20)

3991    141.0000
4177    131.8750
5821    123.0000
3810    120.5000
4386    118.5714
5011    118.0000
3783    113.6667
6045    113.0000
4612    113.0000
4618    109.8333
5352    109.0000
3397    105.6667
6676    104.6667
4785     96.6000
5261     96.0000
3430     95.2500
6747     94.0000
5619     94.0000
6678     94.0000
3985     93.0000
Name: R_avg_SIG_STR_landed, dtype: float64

In [25]:
df.loc[3991, [
    "R_fighter",
    "date",
    "R_avg_SIG_STR_landed",
    "R_total_rounds_fought",
    "R_wins",
    "R_losses"
]]

R_fighter                Sean O'Malley
date                        2018-03-03
R_avg_SIG_STR_landed             141.0
R_total_rounds_fought                3
R_wins                               1
R_losses                             0
Name: 3991, dtype: object

In [26]:
df.loc[3991]

R_fighter          Sean O'Malley
B_fighter     Andre Soukhamthath
R_odds                    -145.0
B_odds                     125.0
R_ev                     68.9655
                     ...
b_dec_odds                 475.0
r_sub_odds                 650.0
b_sub_odds                 650.0
r_ko_odds                  375.0
b_ko_odds                  215.0
Name: 3991, Length: 118, dtype: object